services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: quickbite_core_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: boot_postgres
      POSTGRES_DB: postgres
    # ports:
    #   - "5432:5432"
    volumes:  
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/docker/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 10
  

  redis:
    image: redis:7-alpine
    # ports:
    #   - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 10  
      
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      # - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics","-q","ping"]
      interval: 10s
      retries: 10

  migration-runner:
    build: 
      context: .
      target: migration
    command: ["npx", "tsx", "scripts/migrate-all.ts"]
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy

  core-service:
    build: 
      context: .
      target: production
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - default
      - quickbite-network
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migration-runner:
        condition: service_completed_successfully

  core-worker:
    build: 
      context: .
      target: production
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - default
      - quickbite-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migration-runner:
        condition: service_completed_successfully
networks:
  quickbite-network:
    external: true
volumes:
  postgres-data:



  
